version: 2

project_name: clash-tools

before:
  hooks:
    - go mod tidy

builds:
  - id: clash-tools
    main: ./cmd/clash_tools
    binary: clash-tools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      # Go build info 会自动记录从 tag 推导出的版本，
      # 这里预留位置，如果以后需要以 ldflags 注入版本信息可在代码中使用变量。

archives:
  - id: binaries
    builds:
      - clash-tools
    # 直接发布二进制文件，而不是打包成压缩包
    format: binary
    # 带上版本、OS、架构信息；Windows 下自动补上 .exe
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapshot:
  name_template: "{{ .Tag }}-next"


